# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Vishal Zambre"
email: v.zambre@gmail.com
designation: "Software Architect | Remote Team Lead | React Rails Engineer | DevOps | Fullstack"
description: >- # this means to ignore newlines until "baseurl:"
  Experienced Software Architect and Remote Team Lead with 12+ years in Ruby on Rails, React, and DevOps.
  OSS contributor to Rails and Spree, passionate about clean code, TDD/BDD practices, and modern development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vishalzambre.github.io" # the base hostname & protocol for your site
twitter_username: vzambre
github_username: vishalzambre
linkedin_username: vishalzambre
keywords: "vishal, zambre, software architect, ruby on rails, react, devops, remote team lead, fullstack developer, jekyll, spree, aws, docker, kubernetes"

# SEO and Social
author: "Vishal Zambre"
social:
  name: "Vishal Zambre"
  links:
    - "https://twitter.com/vzambre"
    - "https://github.com/vishalzambre"
    - "https://linkedin.com/in/vishalzambre"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate

# Portfolio specific settings
##################
# Experience #
##################
joning-date: '2012-01-11'
total_experience: 12
specializations:
  - "Ruby on Rails"
  - "React.js"
  - "DevOps & Cloud"
  - "Team Leadership"
  - "System Architecture"

##################
# Contact Info #
##################
location: "India"
availability: "Available for Remote Work"
response_time: "Within 24 hours"

##################
# Social Links #
##################
social_links:
  github: "https://github.com/vishalzambre"
  linkedin: "https://linkedin.com/in/vishalzambre"
  twitter: "https://twitter.com/vzambre"
  stackoverflow: "https://stackoverflow.com/users/2045909/vishal-zambre"
  blog: "https://vishalzambre.blogspot.in"
  website: "https://vishalzambre.com"

##################
# Analytics #
##################
google-tracking-id: "GTM-W8L2CV5N"

##################
# Blog Settings #
##################
post-preview-words: 10
# show_excerpts: true
paginate: 10

##################
# Comments #
##################
disqus:
  name: "vishalzambre"
  noscript: 'Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a>'

##################
# Social Sharing #
##################
email-share: true
twitter-share: true
linkedin-share: true

##################
# Portfolio Stats #
##################
stats:
  experience_years: 12
  projects_completed: 50
  open_source_contributions: 10
  technologies_mastered: 25

##################
# Key Skills #
##################
skills:
  backend:
    - "Ruby (1.9.x, 2.x.x, 3.x.x)"
    - "Ruby on Rails (3.x.x to 7.x.x)"
    - "RESTful APIs"
    - "JBuilder & Serializers"
    - "Rails Engines"
    - "Sinatra"
    - "Spree Commerce"

  frontend:
    - "JavaScript (ES6+)"
    - "React.js"
    - "AngularJS"
    - "HTML5 & CSS3"
    - "jQuery"
    - "HAML & SASS"

  databases:
    - "PostgreSQL"
    - "MySQL"
    - "Redis"
    - "Elasticsearch"
    - "Snowflake"

  devops:
    - "AWS (EC2, S3, ECS, Kinesis)"
    - "Docker & Kubernetes"
    - "Ansible"
    - "Nginx, Passenger, Unicorn"
    - "Capistrano"
    - "Heroku"
    - "Rancher"

  testing:
    - "RSpec"
    - "Cucumber"
    - "TDD/BDD"
    - "GitHub Actions"
    - "Jenkins"
    - "Circle CI"
    - "Semaphore"

##################
# Timeline Events #
##################
events:
  - image: "/img/timeline/open-source.jpg"
    date: "May 2017 - Present"
    description: "Working as Remote Team Lead, Software Architect, and React Rails Engineer. Leading distributed teams and architecting scalable solutions."
  - image: "/img/timeline/spidertocat.png"
    date: "June 2014 - May 2017"
    description: "Senior Software Engineer at Weboniselab, developing complex applications and enterprise solutions."
  - image: "/img/timeline/start-coding.jpg"
    date: "November 2012 - June 2014"
    description: "Started professional journey at Anchanto, building e-commerce platforms and learning enterprise development."

##################
# Featured Projects #
##################
featured_projects:
  - name: "Xneelo Hosting Platform"
    description: "Leading hosting provider in South Africa"
    tech_stack: ["Ruby 3.0", "Rails 7.0", "React", "PostgreSQL", "AWS", "Kubernetes"]
    period: "May 2017 - Present"
    role: "Remote Team Lead | Software Architect"

  - name: "Amazon Marketplace Integration"
    description: "Multi-country marketplace platform for ads and campaigns"
    tech_stack: ["Ruby 3.0", "Rails 7.0", "React", "PostgreSQL", "Snowflake"]
    period: "2017 - 2020"
    role: "Software Architect with Team Lead"

  - name: "DataMapper Cloud Platform"
    description: "Rails & Java platform for drone data management"
    tech_stack: ["Ruby 1.9.3", "Rails 3.2.17", "Java", "MySQL", "AWS SDK"]
    period: "Jun 2014 - May 2017"
    role: "Developer"

# Collections for blog posts and projects
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults for different content types
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Vishal Zambre"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# SEO Plugin Settings
tag_array: ["ruby", "rails", "react", "devops", "software-architecture", "remote-work", "fullstack"]

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.md
