
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: 'https://vishalzambre.github.io'

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: https://vishalzambre.github.io

# Google tracking id

google-tracking-id: "UA-96026950-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Vishal Zambre"
title: "Vishal Zambre's Blog"
description: "Blog and website of Vishal Zambre, blogging mainly for tech. Opinions expressed are mine."
keywords: "vishal, zambre, personal, jekyll, theme, ruby, spree, rails, nginx, install, ssl, lets encrypt"
favicon: "/img/favicon.ico"

################
# Header layout #
################
background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

me-img: "/img/jetpacktocat.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 10

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "zambre-in"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/open-source.jpg"
    date: "April 2017 - Today"
    description: "Working as Remote Ruby Engineer, Learning new geeky things and contributing to open source"
  - image: "/img/timeline/spidertocat.png"
    date: "June 2014 - April 2017"
    description: "Started journey with Weboniselab"
  - image: "/img/timeline/start-coding.jpg"
    date: "November 2012 - June 2014"
    description: "Started coding at Anchanto"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "v.zambre@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Vishal Zambre is an awesome person. He lives in Pune, India, where he works on web and e-commerce projects. In his spare time, Vishal likes to visit new places."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/vishal.zambre"
  - title: "twitter"
    url: "https://twitter.com/vzambre"
  - title: "github"
    url: "https://github.com/vishalzambre"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# Joining Date #
#################
joning-date: '2012-01-11'
##################
# GPG on Keybase #
##################

keybase-username: vishalzambre
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
