version: '3.1'
services:
  site:
    command: jekyll s --drafts --future --force_polling --livereload --host lvh.me
    image: jekyll-vishal:latest
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
    extra_hosts:
      - "lvh.me:0.0.0.0"
